apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  namespace: nginx
  labels:
    app: local
spec:
  capacity:
    storage: 1Gi           # Size of the volume
  accessModes:
    - ReadWriteOnce        # Can be mounted by a single node at a time
  persistentVolumeReclaimPolicy: Retain  # Keep data even if PVC is deleted
  storageClassName: local-storage
  hostPath:
    path: /mnt/backup      # Path on the node's filesystem

