apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  namespace: nginx
spec:
  accessModes:
    - ReadWriteOnce         # Same as PV's access mode
  resources:
    requests:
      storage: 1Gi          # Same size or less than PV
  storageClassName: local-storage

